brew cask install appcleaner
brew cask install alfred
brew cask install dropbox
brew cask install nvalt
brew cask install sourcetree
brew cask install atom
brew cask install iterm2
brew cask install the-unarchiver
brew cask install android-studio
